import { beforeEach, describe, expect, it, vi } from 'vitest';
import { buildNotionBillingSnapshotProperties, publishableBillingSnapshots, publishNotionBillingSnapshots } from './notion-billing-publisher';

const prismaMock = vi.hoisted(() => ({
  contract: {
    findUnique: vi.fn(),
  },
  billingSnapshot: {
    findMany: vi.fn(),
    update: vi.fn(),
  },
}));

const contractsMock = vi.hoisted(() => ({
  resolveContractId: vi.fn(),
}));

vi.mock('./prisma', () => ({
  default: prismaMock,
}));

vi.mock('./contracts', () => contractsMock);

function snapshot(overrides = {}) {
  return {
    id: 'snapshot-1',
    notionDatabaseId: 'APP_GENERATED_MONTHLY_BILLING',
    notionPageId: 'APP_GENERATED:2026-05:site-1',
    notionContractPageId: 'contract-page-1',
    billingEntry: 'Example Site 2026-05',
    billingPeriod: new Date('2026-05-01T00:00:00.000Z'),
    month: '2026-05',
    siteName: 'Example Site',
    spvCode: 'OS2',
    spvName: 'Olympus Solar 2 Ltd',
    appliedTier: '<20MW',
    provider: 'O&M Tracker',
    paymentStatus: 'NOT_INVOICED',
    expectedAmount: 123.45,
    invoicedAmount: null,
    varianceAmount: null,
    variancePercent: null,
    varianceFlag: null,
    proRataFactor: 1,
    invoiceReference: 'INV-001',
    notes: 'Generated by test',
    systemSizeKwp: 1000,
    siteFixedCostsAnnual: 200,
    variableCostAnnual: 1200,
    annualFee: 1400,
    sourcePayload: '{"source":"APP_GENERATED"}',
    billingRunId: 'run-1',
    ...overrides,
  };
}

describe('Notion billing publisher', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    contractsMock.resolveContractId.mockResolvedValue('contract-1');
    prismaMock.contract.findUnique.mockResolvedValue({ notionBillingDatabaseId: null });
  });

  it('builds only writable Notion billing properties', () => {
    const properties = buildNotionBillingSnapshotProperties(snapshot());

    expect(properties).toMatchObject({
      'Billing Entry': { title: [{ text: { content: 'Example Site 2026-05' } }] },
      'O&M Contract': { relation: [{ id: 'contract-page-1' }] },
      'Billing Period': { date: { start: '2026-05-01' } },
      SPV: { select: { name: 'OS2' } },
      'Applied Tier': { select: { name: '<20MW' } },
      'O&M Provider': { select: { name: 'O&M Tracker' } },
      'Payment Status': { status: { name: 'NOT_INVOICED' } },
      'Pro-rata Factor': { number: 1 },
      'Invoice Reference': { rich_text: [{ text: { content: 'INV-001' } }] },
    });

    expect(properties).not.toHaveProperty('Expected Amount (£)');
    expect(properties).not.toHaveProperty('Variance');
    expect(properties).not.toHaveProperty('Variance Amount (£)');
    expect(properties).not.toHaveProperty('Variance Percent');
    expect(JSON.stringify(properties.Notes)).toContain('Expected Amount (£): £123.45');
    expect(JSON.stringify(properties.Notes)).toContain('Source: APP_GENERATED');
  });

  it('omits optional Notion properties when source data is blank', () => {
    const properties = buildNotionBillingSnapshotProperties(
      snapshot({
        notionContractPageId: '',
        spvCode: null,
        spvName: null,
        appliedTier: null,
        provider: null,
        paymentStatus: null,
        proRataFactor: null,
        invoiceReference: null,
      })
    );

    expect(properties).not.toHaveProperty('O&M Contract');
    expect(properties).not.toHaveProperty('SPV');
    expect(properties).not.toHaveProperty('Applied Tier');
    expect(properties).not.toHaveProperty('O&M Provider');
    expect(properties).not.toHaveProperty('Payment Status');
    expect(properties).not.toHaveProperty('Pro-rata Factor');
    expect(properties).not.toHaveProperty('Invoice Reference');
  });

  it('filters snapshots by resolved contract before syncing', async () => {
    prismaMock.billingSnapshot.findMany.mockResolvedValue([]);

    await publishNotionBillingSnapshots({
      month: '2026-05',
      contractId: 'contract-code',
    });

    expect(contractsMock.resolveContractId).toHaveBeenCalledWith('contract-code');
    expect(prismaMock.billingSnapshot.findMany).toHaveBeenCalledWith({
      where: {
        contractId: 'contract-1',
        month: '2026-05',
        source: 'APP_GENERATED',
        OR: [{ notionSyncStatus: null }, { notionSyncStatus: { not: 'SYNCED' } }],
      },
      orderBy: [{ siteName: 'asc' }, { billingEntry: 'asc' }],
    });
  });
});

describe('publishableBillingSnapshots', () => {
  const snapshot = (billingPortfolio: string, id: string) => ({
    id,
    sourcePayload: JSON.stringify({ site: { billingPortfolio } }),
  });

  it('drops Eden rows from a mixed contract so they never reach the host Notion database', () => {
    const rows = [snapshot('CORE', 'core-1'), snapshot('EDEN', 'eden-1')];

    expect(publishableBillingSnapshots(rows as never).map((row) => (row as { id: string }).id)).toEqual(['core-1']);
  });

  it('publishes Eden rows when the contract is entirely Eden', () => {
    const rows = [snapshot('EDEN', 'eden-1'), snapshot('EDEN', 'eden-2')];

    expect(publishableBillingSnapshots(rows as never).map((row) => (row as { id: string }).id)).toEqual(['eden-1', 'eden-2']);
  });

  it('leaves a contract with no Eden rows untouched', () => {
    const rows = [snapshot('CORE', 'core-1'), snapshot('CORE', 'core-2')];

    expect(publishableBillingSnapshots(rows as never)).toHaveLength(2);
  });
});
